branches:
  only:
    - master
language: php
php:
  - "5.3"
before_script:
  - composer require --dev bit3/php-coding-standard:@dev
  - composer require --dev squizlabs/php_codesniffer:1.*
script: ant
